In [10]:
#PROBLEM 1 ARRAY CREATION
#TASK1
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


In [14]:
#TASK2
import numpy as np
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
#TASK3
import numpy as np
fill_array = np.full((2, 2), 8)
print(fill_array)

[[8 8]
 [8 8]]


In [18]:
#TASK4
import numpy as np

given_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
zeros_like_array = np.zeros_like(given_array)

print(given_array)
print(zeros_like_array)

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


In [21]:
#TASK5
import numpy as np

given_array = np.array([[10, 20, 30], [40, 50, 60]], dtype=int)
ones_like_array = np.ones_like(given_array)

print(given_array)
print(ones_like_array)

[[10 20 30]
 [40 50 60]]
[[1 1 1]
 [1 1 1]]


In [22]:
#TASK6
import numpy as np

new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)

print(new_list)
print(array_from_list)

[1, 2, 3, 4]
[1 2 3 4]


In [23]:
#PROBLEM 2
#TASK1
import numpy as np
array_range = np.arange(10, 50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [27]:
#TASK2
import numpy as np
array_1d = np.arange(9)
matrix_3x3 = array_1d.reshape((3, 3))
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
#TASK3
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
#TASK4
import numpy as np

random_array = np.random.random(30)
array_mean = random_array.mean()

print(random_array)
print(array_mean)

[0.06818505 0.35427064 0.69364638 0.46978114 0.59054624 0.87147414
 0.60181215 0.40906059 0.60035676 0.03231899 0.21280339 0.17803688
 0.08423838 0.05586525 0.21390013 0.58346295 0.71121743 0.80305093
 0.55932846 0.89902632 0.47615403 0.95492615 0.87700013 0.75196038
 0.05840507 0.65009075 0.44085913 0.40913385 0.5758172  0.92719164]
0.5037973512575796


In [85]:
#TASK5
import numpy as np

random_array = np.random.rand(10, 10)
min_value = random_array.min()
max_value = random_array.max()
print(random_array)

print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")


[[9.59545871e-01 8.44049283e-01 8.30397219e-01 9.56510577e-01
  6.76873637e-01 4.19651438e-01 5.55700895e-01 4.23832222e-01
  6.48519316e-01 5.34223654e-01]
 [4.24622532e-01 9.51868634e-01 2.34620623e-01 7.38175480e-01
  3.75310799e-01 3.10650012e-01 8.75722795e-01 3.35171680e-01
  5.62625440e-01 6.19054639e-01]
 [1.11586839e-01 9.75760336e-01 9.57911757e-01 2.50940472e-01
  9.54643481e-01 2.49989662e-01 7.71346262e-01 9.29862219e-01
  1.34661513e-01 1.04856384e-02]
 [3.28557908e-01 6.02828795e-01 3.01960559e-01 9.24183123e-01
  5.53447466e-01 5.30423163e-01 9.95840006e-01 1.14592158e-01
  7.37767995e-01 8.43077263e-01]
 [4.34988358e-01 4.23363872e-01 5.35379044e-01 5.78517844e-01
  6.55742050e-01 9.24770403e-01 8.45713711e-01 5.22848763e-02
  2.54349514e-01 5.87198510e-01]
 [4.96853357e-01 5.08825407e-01 3.60639357e-01 8.87194954e-01
  2.62041519e-01 4.63165266e-01 1.79959521e-01 7.17016018e-01
  2.30515853e-01 4.88064211e-01]
 [8.75999805e-01 5.46245236e-01 8.91080972e-01 3.20921253e

In [31]:
#TASK6
import numpy as np
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [33]:
#TASK6
import numpy as np
arr = np.array([1,2,0,0,4,0])
reverse_array = np.flip(arr)
print(reverse_array)

[0 4 0 0 2 1]


In [37]:
#TASK7
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [45]:
#TASK8
import numpy as np

array = np.zeros((4, 4), dtype=int)
array[0, :] = 1  
array[-1, :] = 1 
array[:, 0] = 1  
array[:, -1] = 1  

print(array)


[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [62]:
#TASK9
import numpy as np
arr = np.zeros((4, 4), dtype=int)
arr[1::2, 0::2] = 5
arr[::2, 1::2] = 5
print(arr)

[[0 5 0 5]
 [5 0 5 0]
 [0 5 0 5]
 [5 0 5 0]]


In [76]:
#PROBLEM 3 ARRAY OPERATIONS
#TASK1
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10]) 
w = np.array([11,12])
result_1 = np.add(x,y) 
result_2 = np.add(v,w)
addition = np.add(result_1, result_2)

print(result_1)
print(result_2)
print(addition)

[[ 6  8]
 [10 13]]
[20 22]
[[26 30]
 [30 35]]


In [78]:
#TASK2
import numpy as np

a = np.array([[1,2],[3,5]])
b = np.array([[5,6],[7,8]])
v = np.array([9,10]) 
w = np.array([11,12])

result_1 = np.subtract(a,b) 
result_2 = np.subtract(v,w)
subtraction = np.subtract(result_1, result_2)

print(result_1)
print(result_2)
print(subtraction)

[[-4 -4]
 [-4 -3]]
[-2 -2]
[[-2 -2]
 [-2 -1]]


In [79]:
#TASK3
import numpy as np

c = np.array([[1,4], [0,3]])
d = np.array([[0,3], [1,4]])
v = np.array([9,10]) 
w = np.array([11,12])

result_1 = np.multiply(c,d) 
result_2 = np.multiply(v,w)
multiplication = np.multiply(result_1, result_2)

print(result_1)
print(result_2)
print(multiplication)

[[ 0 12]
 [ 0 12]]
[ 99 120]
[[   0 1440]
 [   0 1440]]


In [89]:
#TASK4
import numpy as np

v = np.array([9, 10])
w = np.array([11, 12])
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result_1 = np.square(v,w)
result_2 = np.square(x,y)

print(result_1)
print(result_2)

[ 81 100]
[[ 1  4]
 [ 9 25]]


In [84]:
#TASK5
import numpy as np

v = np.array([9, 10])
w = np.array([11, 12])
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

dot_product_vw = np.dot(v, w)
dot_product_xv = np.dot(x, v)
dot_product_xy = np.dot(x, y)

print(f"Dot product of v and w: {dot_product_vw}")
print(f"Dot product of x and v: {dot_product_xv}")
print(f"Dot product of x and y: {dot_product_xy}")


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


In [87]:
#TASK6
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# CONCATENATE X AND Y ALONG ROWS (AXIS=0)
#CONCAT_XY_ROWS = np.concatenate((x, y), axis=0)

# CONCATENATE V AND W ALONG COLUMNS (AXIS=1)
#CONCAT_VW_COLUMNS = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

concat_vw_columns_vstack = np.vstack((v, w)).T 

print(f"Concatenated v and w along columns (using np.vstack):\n{concat_vw_columns_vstack}")


Concatenated v and w along columns (using np.vstack):
[[ 9 11]
 [10 12]]


In [104]:
#TASK7
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_xv_rows = np.concatenate((x, v.reshape(1, -1)), axis=0)
print(f"Concatenation:\n{concat_xv_rows}")

concat_xv_columns = np.concatenate((x, v.reshape(-1, 1)), axis=1)
print(f"Concatenation:\n{concat_xv_columns}")

Concatenation:
[[ 1  2]
 [ 3  5]
 [ 9 10]]
Concatenation:
[[ 1  2  9]
 [ 3  5 10]]


In [107]:
# PROBLEM 4 MATRIX OPERATIONS
#A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]); Prove following with Numpy:
#1.	Prove A.A−1 = I.

import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print(result)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [109]:
#2.	Prove AB ̸= BA
import numpy as np

B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [110]:
#3 Prove (AB)T = BTAT

import numpy as np

AB_transpose = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("(AB)^T:\n", AB_transpose)
print("B^T * A^T:\n", BT_AT)


(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]


In [113]:
#4 •	Solve the following system of Linear equation using Inverse Methods.
#2x − 3y + z = −1 x − y + 2z = −3 3x + y − z = 9

import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution:", X)

Solution: [ 2.  1. -2.]


In [114]:
#5 solve the above equation using np.linalg.inv function.
#{Explore more about ”linalg” function of Numpy}

import numpy as np

X_solve = np.linalg.solve(A, B)
print("Solution using np.linalg.solve:", X_solve)


Solution using np.linalg.solve: [ 2.  1. -2.]
